version: "3.9"
volumes:
  vendors:

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports:
      - "8081:80"
    volumes:
      - "../src:/var/www/html:rw"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel
  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3310:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    volumes:
      - "../src:/var/www/html:rw"
      - "vendors:/var/www/html/vendor"
    build:
      context: ../
      dockerfile: docker/DockerFile
    container_name: laravel_php
    ports:
      - "9000:9000"
    networks:
      - laravel
